name: preliz-docs
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.11
  - matplotlib>=3.8
  - numba>=0.60
  - numpy>=2.0
  - scipy>=1.12
  - nbclient>=0.2
  - ipywidgets
  - ipympl
  - jupyterlab
  - notebook
  - pydata-sphinx-theme>=0.6.3
  - myst-nb
  - sphinx>=4
  - sphinx-copybutton
  - sphinx-tabs
  - sphinxcontrib-bibtex
  - jupyter-sphinx
  - pymc>=5.24.0
  - bambi>=0.15.0
