name: preliz-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python >= 3.11
  - pip
  - matplotlib>=3.7
  - numba>=0.59
  - numpy>=1.24
  - scipy>=1.10
  - nbclient>=0.2
  - ipywidgets
  - ipympl
  - jupyterlab
  - notebook
  - black==22.3.0
  - click
  - pytest-cov>=2.6.1
  - pytest>=4.4.0
  - pre-commit>=2.19
  - nbconvert
  - nbformat
  - ruff
  - ipykernel
  - pymc>=5.16.0
  - bambi>=0.13.0
  - pip:
      - lxml
      - ipytest
